// Tiny localisation table for fixed acknowledgment messages the system
// posts on the user's behalf (not generated by the agent). Keeps the
// language consistent with repo.language_for_communication without
// burning a Claude turn on every "Беру в работу".
//
// Every message starts with the BOT_PREFIX so it is both visible to
// humans AND used by the feedback filter to drop the agent's own posts.
//
// BOT_PREFIX is configurable via OPENRONIN_BOT_PREFIX env var. Pick anything
// distinctive that is unlikely to appear at the start of a human's comment —
// the bot's self-loop filter relies on it.

const RU = "Russian";
const EN = "English";

export const BOT_PREFIX = process.env.OPENRONIN_BOT_PREFIX ?? "🤖 openronin:";

export function isBotMessage(text: string): boolean {
  const trimmed = text.trimStart();
  return trimmed.startsWith(BOT_PREFIX) || text.includes("<!-- openronin:bot -->");
}

// Who may steer the agent through comments. Anyone can comment on a PR in a
// public repo, and pr_dialog / analyze feed comment text straight into an
// agent prompt that runs with git-write tools — so by default only the repo's
// own people count. `null` in config disables the filter (legacy behaviour).
export const DEFAULT_TRUSTED_COMMENT_ASSOCIATIONS = ["OWNER", "MEMBER", "COLLABORATOR"];

export function isTrustedCommentAuthor(
  association: string | undefined,
  trusted: readonly string[] | null | undefined,
): boolean {
  if (trusted === null || trusted === undefined) return true;
  // Providers that do not expose an association (GitLab, trackers) are not
  // filtered: there is nothing to decide on, and dropping every comment would
  // silently break them.
  if (association === undefined) return true;
  return trusted.includes(association.toUpperCase());
}

export function withPrefix(text: string): string {
  return text.startsWith(BOT_PREFIX) ? text : `${BOT_PREFIX} ${text}`;
}

interface Lang {
  taking_in_progress: string;
  pr_opened: (prNumber: number) => string;
  patch_failed: (reason: string) => string;
  patch_blocked: (reason: string) => string;
  ack_received: string;
  iteration_pushed: (
    iter: number,
    summary: string,
    files: number,
    added: number,
    removed: number,
  ) => string;
  no_action_needed: (summary: string) => string;
  iteration_blocked: (reason: string) => string;
  auto_merged: (strategy: string, sha: string) => string;
  auto_merge_blocked: (reason: string) => string;
  conflict_resolve_started: (baseRef: string) => string;
  conflict_resolve_succeeded: (filesResolved: number, newSha: string) => string;
  conflict_resolve_failed: (reason: string) => string;
  conflict_resolve_capped: (limit: number) => string;
  analyze_questions_intro: string;
  analyze_questions_outro: string;
  analyze_ready_intro: string;
  analyze_summary_label: string;
  analyze_requirements_label: string;
  analyze_files_label: string;
}

const LANGS: Record<string, Lang> = {
  [RU]: {
    taking_in_progress: `${BOT_PREFIX} беру задачу в работу. Открою PR через несколько минут.`,
    pr_opened: (n) => `${BOT_PREFIX} готово — открыт черновик PR #${n}.`,
    patch_failed: (reason) =>
      `${BOT_PREFIX} не получилось выполнить задачу автоматически: ${reason}`,
    patch_blocked: (reason) =>
      `${BOT_PREFIX} изменения подготовлены, но заблокированы предохранителем: ${reason}`,
    ack_received: `${BOT_PREFIX} принял замечание, начинаю итерацию.`,
    iteration_pushed: (iter, summary, files, added, removed) =>
      `${BOT_PREFIX} итерация ${iter} — изменения запушены.\n\n${summary}\n\n**Изменено в этой итерации:** ${files} файлов, +${added} / -${removed}.`,
    no_action_needed: (summary) =>
      `${BOT_PREFIX} прочитал замечание, изменения не нужны. Причина:\n\n${summary}\n\nPR помечен как требующий внимания человека.`,
    iteration_blocked: (reason) =>
      `${BOT_PREFIX} итерация заблокирована предохранителем — ${reason}. Изменения не запушены, PR требует внимания человека.`,
    auto_merged: (strategy, sha) =>
      `${BOT_PREFIX} нерешённых вопросов нет, проверки прошли — выполнил автоматический ${strategy} (${sha.slice(0, 7)}). Закрываю PR.`,
    auto_merge_blocked: (reason) =>
      `${BOT_PREFIX} автомердж пропущен: ${reason}. PR остаётся открытым на ваше решение.`,
    conflict_resolve_started: (baseRef) =>
      `${BOT_PREFIX} обнаружены конфликты с \`${baseRef}\` — пробую разрешить через rebase.`,
    conflict_resolve_succeeded: (filesResolved, newSha) =>
      `${BOT_PREFIX} конфликты разрешены автоматически в ${filesResolved} файл(ах), ветка пересобрана (${newSha.slice(0, 7)}). Возвращаюсь к авто-мерджу.`,
    conflict_resolve_failed: (reason) =>
      `${BOT_PREFIX} не удалось автоматически разрешить конфликты: ${reason}. PR требует ручного rebase.`,
    conflict_resolve_capped: (limit) =>
      `${BOT_PREFIX} лимит автоматических разрешений конфликтов достигнут (${limit}). Дальше — только вручную.`,
    analyze_questions_intro: "прежде чем брать в работу, нужно уточнить несколько моментов.",
    analyze_questions_outro:
      "Ответь на вопросы в комментарии — как только будет ясность, я возьму задачу в работу.",
    analyze_ready_intro: "разобрал задачу. Принимаю в работу — открою PR через несколько минут.",
    analyze_summary_label: "Понимание задачи",
    analyze_requirements_label: "Что собираюсь сделать",
    analyze_files_label: "Вероятно затронутые файлы",
  },
  [EN]: {
    taking_in_progress: `${BOT_PREFIX} picking this up. Will open a PR in a few minutes.`,
    pr_opened: (n) => `${BOT_PREFIX} done — draft PR #${n} opened.`,
    patch_failed: (reason) => `${BOT_PREFIX} could not complete the task automatically: ${reason}`,
    patch_blocked: (reason) =>
      `${BOT_PREFIX} changes were made but a guardrail blocked the push: ${reason}`,
    ack_received: `${BOT_PREFIX} acknowledged — starting an iteration.`,
    iteration_pushed: (iter, summary, files, added, removed) =>
      `${BOT_PREFIX} iteration ${iter} — pushed updates.\n\n${summary}\n\n**Changed this iteration:** ${files} files, +${added} / -${removed}.`,
    no_action_needed: (summary) =>
      `${BOT_PREFIX} read the feedback. No code changes needed. Reasoning:\n\n${summary}\n\nThis PR is now flagged for human attention.`,
    iteration_blocked: (reason) =>
      `${BOT_PREFIX} iteration blocked by a guardrail — ${reason}. The proposed changes were not pushed and the PR needs human attention.`,
    auto_merged: (strategy, sha) =>
      `${BOT_PREFIX} no open questions and checks are green — performed an automatic ${strategy} (${sha.slice(0, 7)}). Closing PR.`,
    auto_merge_blocked: (reason) =>
      `${BOT_PREFIX} auto-merge skipped: ${reason}. PR stays open for your decision.`,
    conflict_resolve_started: (baseRef) =>
      `${BOT_PREFIX} merge conflicts with \`${baseRef}\` detected — attempting an automated rebase.`,
    conflict_resolve_succeeded: (filesResolved, newSha) =>
      `${BOT_PREFIX} resolved conflicts in ${filesResolved} file(s) automatically and rebased the branch (${newSha.slice(0, 7)}). Returning to auto-merge.`,
    conflict_resolve_failed: (reason) =>
      `${BOT_PREFIX} couldn't resolve conflicts automatically: ${reason}. Please rebase manually.`,
    conflict_resolve_capped: (limit) =>
      `${BOT_PREFIX} reached the auto conflict-resolution limit (${limit}). Further attempts must be manual.`,
    analyze_questions_intro: "before I start coding, I need to clarify a few things.",
    analyze_questions_outro: "Reply in this thread; once it's clear, I'll pick up the task.",
    analyze_ready_intro: "analysed the task. Picking it up — will open a PR in a few minutes.",
    analyze_summary_label: "Understanding",
    analyze_requirements_label: "What I plan to do",
    analyze_files_label: "Likely touched files",
  },
};

export function pick(language: string): Lang {
  return LANGS[language] ?? LANGS[EN]!;
}
